[desktop/interface]
color-scheme='prefer-dark'
font-name='Ubuntu Sans 11'
gtk-enable-primary-paste=true
gtk-theme='Yaru-dark'
icon-theme='Yaru-dark'
show-battery-percentage=true

[desktop/privacy]
report-technical-problems=false
