[vitals]
hot-sensors=['_memory_usage_', '__network-rx_max__', '_temperature_thinkpad_cpu_', '_processor_usage_']
include-static-gpu-info=false
menu-centered=true
position-in-panel=1
show-battery=true
show-fan=false
show-gpu=false
show-voltage=false
